sudo: required
language: python
python:
- '2.6'
- '2.7'
services:
- docker
before_install:
- docker pull pythea/ldap
- docker run -d --net=host --name ldap pythea/ldap
- docker ps -a
- sudo apt -y install ldap-utils python-flake8
- git clone https://github.com/sstephenson/bats.git && sudo bats/install.sh /usr/local
- docker logs ldap
install:
- sudo pip install -r requirements.txt
- sudo python setup.py -q install
script:
- flake8 obol
- bats tests/tests
deploy:
  provider: pypi
  user: hans.then
  password:
    secure: IBfducwigKHRVbIJkDZ/7GOqDWnicrce6oHnOkInDOiyK/GVcHBMDpTCP9dpk3vnxE16c1cEVeCkzqUGvRjNAY66s2vhspV6CU9pnUAdeHbFLL1thIzyPOKTVuhhekGk1G1dTeHmoYXxnaiv1FdLB1YZZm3GoXGs9ukqDcma/uG4qFYYU2IXrQOBeeu/hA1Jzm0uczxH7WIfsC+izlfv7fM2XB+MYAGqz3zGLwHcxsm1NzXosEreYjVpqCnJFYtPlRZmudFok8YD47UO3Unn3VN4FXw1Q47ZsQWNn6UBnMQM/OEUgMle2tyHewpNd51BUqS+o//i51lST6qX97J9TLnKdH4g6HSH8ByZgDIHz+Jci+gc8VcOKelntVIDiktHCFKj5UvvipPPAJQlBqvpRG6ySvk7AoUhNgxwKQhTcB4M/xenOegekOEBI3tN5i3DzuoyL1PgA5YWKL2XN9/I9k5ScCY/fxtsGDg4BXU5SH8T4xw7ObJsFD+MVV38qy6oqVe1afe4TObRi4/+E+r/fjrQ98/IP1uEFUjfnCNb0rN0FSDuHwIzBeZnQxnRJ0+6syCqDphNUDLuYyADaSX97mfcvUhl/pvEbj6oXKR8yfk6geuRDzpgRkNglmBkh2z3MqNDYaNBsaQ+SlT+AaMkP7/08XAfM1GhBM0INUCw2wI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: hansthen/obol
