sudo: required

language: python

python:
  - "2.6"
  - "2.7"

services:
  - docker

before_install:
- docker pull pythea/ldap
- docker run -d --net=host --name ldap pythea/ldap 
- docker ps -a
- sudo apt -y install ldap-utils python-flake8
- docker logs ldap

install:
- sudo pip install -r requirements.txt
- sudo python setup.py -q install 

script:
- flake8 obol
- obol -w system init
- docker exec -it ldap ldapsearch -H ldapi:/// -Y EXTERNAL -b 'dc=local'
- obol -w system user list
- obol -w system user add hans
- obol -w system user list

deploy:
  provider: pypi
  user: "Your username"
  password: "Your password"
  on:
    tags: true
