sudo: required

language: python

services:
  - docker

before_install:
- docker pull pythea/ldap
- docker run -d -p127.0.0.1:389:4567 --name ldap pythea/ldap 
- docker ps -a
- sudo apt install ldap-utils
- docker logs ldap
- while ! ldapmodify -H ldap://localhost:389 -a -D cn=Manager,dc=local -w system -f ./tests/setup.ldif; do sleep 1; done

script:
- obol -w system user list
